name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes if you use any
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'  # Use latest or specify a version
        extended: true  # Use Hugo extended if needed

    - name: Build
      run: hugo --minify

    - name: Create .nojekyll
      run: echo "" > ./public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
